package by.victor.beta.entity;

public enum NotifyType {
    REGISTRATION,EMAIL_VALIDATION,ADMIN_VALIDATION,ORDER_NOT_CLAIMED,ORDER_EXECUTION_START,ORDER_EXECUTION_FINISH,
    ORDER_EXECUTOR_REFUSE,ORDER_CANCEL,ORDER_CREATED,CREDIT_ACCOUNT,ORDER_ACCEPTED
}
