package by.victor.beta.entity.util;

public enum NotifyType {
    SIMPLE_TEXT,REGISTRATION,EMAIL_CONFIRMED,ADMIN_VALIDATION,ORDER_NOT_CLAIMED,ORDER_EXECUTION_START, ORDER_EXECUTION_FINISH_TO_EXECUTOR,
    ORDER_EXECUTOR_REFUSE,ORDER_CANCEL_TO_CUSTOMER,ORDER_CANCEL_TO_EXECUTOR,ORDER_CREATED,CREDIT_ACCOUNT,ORDER_ACCEPTED,
    ORDER_EXECUTION_FINISH_TO_CUSTOMER, REGISTRATION_EMAIL_VERIFY_REQUEST
}
